version: "3"
services:
  prisma:
    container_name: prisma
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=prisma
    ports:
      - 5433:5432
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
